New features
Sh1p1lov/JoyDev_Music_Player pull request #2
Opened 2022-01-09 02:29 UTC by Sh1p1lov

Сделал разметку для фрагментов, добавил пустые классы фрагментов, добавил контейнер для фрагментов в макете мэйн активити, добавил фрагменты в граф навигации. Логики пока никакой не писал.

2022-01-11 12:09 UTC, mist962 requested changes

2022-01-11 12:09 UTC, mist962 commented on app/src/main/res/layout/fragment_login.xml
> +
empty line

2022-01-11 12:09 UTC, mist962 commented on app/src/main/res/layout/fragment_main.xml
> +
empty line

2022-01-12 13:36 UTC, Sh1p1lov commented on app/src/main/res/layout/fragment_login.xml
> +
Исправил

2022-01-12 13:36 UTC, Sh1p1lov commented on app/src/main/res/layout/fragment_main.xml
> +
Исправил

2022-01-13 07:12 UTC, mist962 approved these changes

2022-01-18 15:11 UTC, merged