New features 2
Sh1p1lov/JoyDev_Music_Player pull request #3
Opened 2022-01-21 13:50 UTC by Sh1p1lov

Разделил проект на модули, добавил koin, ViewModel, ViewBinding, создал классы валидатора полей ввода, создал некоторые классы юз кейсы

2022-01-24 08:07 UTC, mist962 requested changes

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/validator/PasswordInputFieldValidator.kt
> +    }
когда будет валидация ?

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/validator/LoginInputFieldValidator.kt
> +    }
когда будет валидация ?

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/validator/EmailInputFieldValidator.kt
> +    }
когда будет валидация ?

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/usecase/ValidatePasswordInputFieldUseCase.kt
> +
empty line

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/usecase/ValidateLoginInputFieldUseCase.kt
> +
empty line

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/usecase/ValidateEmailInputFieldUseCase.kt
> +
empty line

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/usecase/RegistrationByEmailUseCase.kt
> +    }
?

2022-01-24 08:07 UTC, mist962 commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/repository/UserRepository.kt
> +}
можно убрать {}

2022-01-24 08:07 UTC, mist962 commented on domain/build.gradle
> +    targetCompatibility = JavaVersion.VERSION_1_7
1.7 не актуально, 1_8

2022-01-24 08:07 UTC, mist962 commented on domain/build.gradle
> +java {
вообще не видел никогда чтобы так тащили что-то тамщи стандартным android, мы на джаве не пишем

2022-01-24 08:07 UTC, mist962 commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DomainModule.kt
> +            maxTextLength = MAX_LOGIN_TEXT_LENGTH
зачем ты сюда кидаешь в конструкторы ? Внутри класса никак не заюзать ?

2022-01-24 08:07 UTC, mist962 commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DomainModule.kt
> +                maxTextLength = MAX_EMAIL_TEXT_LENGTH
выше вопрос

2022-01-24 08:07 UTC, mist962 commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DomainModule.kt
> +                maxTextLength = MAX_PASSWORD_TEXT_LENGTH
выше вопрос

2022-01-24 08:07 UTC, mist962 commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DataModule.kt
> +        object : UserRepository {}
тело обязательно ?

2022-01-24 08:07 UTC, mist962 commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/presentation/fragments/RegistrationFragment.kt
> +                vm.validateLogin(it.toString())
где отобразится ошибка ? не вижу возврщаемого типа и почему только логин валидейт ?

2022-01-29 04:06 UTC, Sh1p1lov commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/validator/PasswordInputFieldValidator.kt
> +    }
Реализовано

2022-01-29 04:06 UTC, Sh1p1lov commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/validator/LoginInputFieldValidator.kt
> +    }
Реализовано

2022-01-29 04:06 UTC, Sh1p1lov commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/validator/EmailInputFieldValidator.kt
> +    }
Реализовано

2022-01-29 04:06 UTC, Sh1p1lov commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/usecase/ValidatePasswordInputFieldUseCase.kt
> +
Исправлено

2022-01-29 04:06 UTC, Sh1p1lov commented on domain/src/main/java/com/sh1p1lov/joydevmusicplayer/domain/usecase/ValidateLoginInputFieldUseCase.kt
> +
Исправлено

2022-01-29 04:07 UTC, Sh1p1lov commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DomainModule.kt
> +            maxTextLength = MAX_LOGIN_TEXT_LENGTH
Переделал

2022-01-29 04:07 UTC, Sh1p1lov commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DomainModule.kt
> +                maxTextLength = MAX_EMAIL_TEXT_LENGTH
Переделал

2022-01-29 04:07 UTC, Sh1p1lov commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DomainModule.kt
> +                maxTextLength = MAX_PASSWORD_TEXT_LENGTH
Переделал

2022-01-29 04:08 UTC, Sh1p1lov commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/di/DataModule.kt
> +        object : UserRepository {}
Это просто временная заглушка, пока нет реализации сохранения регистрируемых юзеров

2022-01-29 04:13 UTC, Sh1p1lov commented on app/src/main/java/com/sh1p1lov/joydevmusicplayer/presentation/fragments/RegistrationFragment.kt
> +                vm.validateLogin(it.toString())
Сделал отображение используя liveData.observe {...}

2022-02-04 10:04 UTC, mist962 approved these changes

2022-02-06 16:24 UTC, merged